# /*******************************************************************************
#  *
#  * Copyright (c) {2022-2023} Francois J. Aouad.
#  * All rights reserved. This program and the accompanying materials
#  * are made available under the terms of the GNU General Public License v3.0
#  * which accompanies this distribution, and is available at
#  * https://www.gnu.org/licenses/gpl-3.0.en.html
#  *
#  *******************************************************************************/

version: '3.7'
services:
  # complete monitoring and Logs setup that uses Prometheus, Grafana, Promtail, Loki and cAdvisor
  webflux:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    container_name: webflux_c
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb_c
    image: mongo:6.0
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    ports:
      - '27017:27017'
    command: mongod --logpath=/dev/null