# /*******************************************************************************
#  *
#  * Copyright (c) {2022-2023} Francois J. Aouad.
#  * All rights reserved. This program and the accompanying materials
#  * are made available under the terms of the GNU General Public License v3.0
#  * which accompanies this distribution, and is available at
#  * https://www.gnu.org/licenses/gpl-3.0.en.html
#  *
#  *******************************************************************************/

# Database
spring:
  data:
    mongodb:
      uri: 'mongodb://mongodb:27017/webflux'
  profiles:
    active: development
  graphql:
    schema:
      locations: 'classpath:graphql'
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql

# App
app:
  jwt:
    accessToken:
      expiry: 60000
      secret: MYsECRETkYE
    refreshToken:
      expiry: 120000
      secret: DSADWEE3R3F
    emailToken:
      expiry: 100000
      secret: MYsECRETkYEDA8E8DD

# YAML
server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus
  endpoint:
    prometheus:
      enabled: true
