# /*******************************************************************************
#  *
#  * Copyright (c) {2022-2023} Francois J. Aouad.
#  * All rights reserved. This program and the accompanying materials
#  * are made available under the terms of the GNU General Public License v3.0
#  * which accompanies this distribution, and is available at
#  * https://www.gnu.org/licenses/gpl-3.0.en.html
#  *
#  *******************************************************************************/

version: '3.7'
services:
  mongodb_exporter:
    image: bitnami/mongodb-exporter:latest
    ports:
      - 9216:9216
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
  sonarqube_exporter:
    image: bitnami/sonarqube-exporter:latest
    ports:
      - 9630:9630
    environment:
      - SONARQUBE_HOST=http://sonarqube:9000
      - SONARQUBE_USERNAME=admin
      - SONARQUBE_PASSWORD=admin
