# /*******************************************************************************
#  *
#  * Copyright (c) {2022-2023} Francois J. Aouad.
#  * All rights reserved. This program and the accompanying materials
#  * are made available under the terms of the GNU General Public License v3.0
#  * which accompanies this distribution, and is available at
#  * https://www.gnu.org/licenses/gpl-3.0.en.html
#  *
#  *******************************************************************************/

version: '3.7'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.0
    container_name: 'logstash_c'
    volumes:
      - '../etc/logstash:/usr/share/logstash/pipeline'
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: 'elastic_c'
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
