# /*******************************************************************************
#  *
#  * Copyright (c) {2022-2023} Francois J. Aouad.
#  * All rights reserved. This program and the accompanying materials
#  * are made available under the terms of the GNU General Public License v3.0
#  * which accompanies this distribution, and is available at
#  * https://www.gnu.org/licenses/gpl-3.0.en.html
#  *
#  *******************************************************************************/

global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'webflux'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'webflux:9000' ]