# /*******************************************************************************
#  *
#  * Copyright (c) {2022-2023} Francois J. Aouad.
#  * All rights reserved. This program and the accompanying materials
#  * are made available under the terms of the GNU General Public License v3.0
#  * which accompanies this distribution, and is available at
#  * https://www.gnu.org/licenses/gpl-3.0.en.html
#  *
#  *******************************************************************************/

#apiVersion: 1
#groups:
#  - orgId: 1
#    name: my_rule_group
#    folder: my_first_folder
#    interval: 60s
#    rules:
#      - uid: my_id_1
#        title: my_first_rule
#        condition: A
#        data:
#          - refId: A
#            datasourceUid: "__expr__"
#            model:
#              conditions:
#                - evaluator:
#                    params:
#                      - 3
#                    type: gt
#                  operator:
#                    type: and
#                  query:
#                    params:
#                      - A
#                  reducer:
#                    type: last
#                  type: query
#              datasource:
#                type: __expr__
#                uid: "__expr__"
#              expression: 1==0
#              intervalMs: 1000
#              maxDataPoints: 43200
#              refId: A
#              type: math
#        dashboardUid: my_dashboard
#        panelId: 123
#        noDataState: Alerting
#        executionErrorState: Alerting
#        for: 60s
#        annotations:
#          some_key: some_value
#        labels:
#          team: sre_team_1
#        isPaused: false
#deleteRules:
#  - orgId: 1
#    uid: my_id_1
#contactPoints:
#  - orgId: 1
#    name: cp_1
#    receivers:
#      - uid: first_uid
#        type: prometheus-alertmanager
#        settings:
#          url: http://localhost:9000
#deleteContactPoints:
#  - orgId: 1
#    uid: first_uid
#policies:
#  - orgId: 1
#    receiver: grafana-default-email
#    group_by:
#      - grafana_folder
#      - alertname
#    matchers:
#      - alertname = Watchdog
#      - severity =~ "warning|critical"
#    mute_time_intervals:
#      - abc
#    group_wait: 30s
#    group_interval: 5m
#    repeat_interval: 4h
#    routes:
#resetPolicies:
#  - 1
#templates:
#  - orgID: 1
#    name: my_first_template
#    template: Alerting with a custome text template
#deleteTemplates:
#  - orgId: 1
#    name: my_first_template
#muteTimes:
#  - orgId: 1
#    name: mti_1
#    time_intervals:
#      - times:
#          - start_time: '06:00'
#            end_time: '23:59'
#        weekdays: ['monday:wednesday','saturday', 'sunday']
#        months: ['1:3', 'may:august', 'december']
#        years: ['2020:2022', '2030']
#        days_of_month: ['1:5', '-3:-1']
#deleteMuteTimes:
#  - orgId: 1
#    name: mti_1