# /*******************************************************************************
#  *
#  * Copyright (c) {2022-2023} Francois J. Aouad.
#  * All rights reserved. This program and the accompanying materials
#  * are made available under the terms of the GNU General Public License v3.0
#  * which accompanies this distribution, and is available at
#  * https://www.gnu.org/licenses/gpl-3.0.en.html
#  *
#  *******************************************************************************/

#apiVersion: 2
#roles:
#  - name: 'custom:users:writer'
#    uid: customuserswriter1
#    description: 'Create, read, write users'
#    version: 2
#    orgId: 1
#    permissions:
#      - action: 'users:read'
#        scope: 'global.users:*'
#      - action: 'users:write'
#        scope: 'global.users:*'
#      - action: 'users:create'
#  - name: 'custom:global:users:reader'
#    global: true
#    state: 'absent'
#    force: true
#  - uid: 'basic_editor'
#    version: 2
#    global: true
#    from:
#      - uid: 'basic_editor'
#        global: true
#      - name: 'fixed:users:writer'
#        global: true
#    permissions:
#      - action: 'users:read'
#        scope: 'global.users:*'
#      - action: 'users:write'
#        scope: 'global.users:*'
#        state: absent
#teams:
#  - name: 'Users writers'
#    orgId: 1
#    roles:
#      - uid: 'customuserswriter1'
#        orgId: 1
#      - name: 'fixed:users:writer'
#        global: true
#        state: absent